//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLeader.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalLeader.Web.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine, Kyiv, Mykhailo Stelmakh Street.
        /// </summary>
        public static string FooterAddress {
            get {
                return ResourceManager.GetString("FooterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are in love with digital world. We believe that information technology is a key to contemporary business success. In twenty first only those businesses will be on the edge of economical prosperity that utilize recent digital trends..
        /// </summary>
        public static string FooterMessage {
            get {
                return ResourceManager.GetString("FooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string LinkBlog {
            get {
                return ResourceManager.GetString("LinkBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string LinkCareer {
            get {
                return ResourceManager.GetString("LinkCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case studies.
        /// </summary>
        public static string LinkCaseStudies {
            get {
                return ResourceManager.GetString("LinkCaseStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string LinkClients {
            get {
                return ResourceManager.GetString("LinkClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string LinkCompany {
            get {
                return ResourceManager.GetString("LinkCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string LinkConnect {
            get {
                return ResourceManager.GetString("LinkConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides.
        /// </summary>
        public static string LinkGuides {
            get {
                return ResourceManager.GetString("LinkGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infographics.
        /// </summary>
        public static string LinkInfographics {
            get {
                return ResourceManager.GetString("LinkInfographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our creed.
        /// </summary>
        public static string LinkOurCreed {
            get {
                return ResourceManager.GetString("LinkOurCreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our story.
        /// </summary>
        public static string LinkOurStory {
            get {
                return ResourceManager.GetString("LinkOurStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team.
        /// </summary>
        public static string LinkOurTeam {
            get {
                return ResourceManager.GetString("LinkOurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts.
        /// </summary>
        public static string LinkPodcasts {
            get {
                return ResourceManager.GetString("LinkPodcasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string LinkPortfolio {
            get {
                return ResourceManager.GetString("LinkPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string LinkProjects {
            get {
                return ResourceManager.GetString("LinkProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string LinkResources {
            get {
                return ResourceManager.GetString("LinkResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string LinkServices {
            get {
                return ResourceManager.GetString("LinkServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string LinkTestimonials {
            get {
                return ResourceManager.GetString("LinkTestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string LinkVideos {
            get {
                return ResourceManager.GetString("LinkVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Papers.
        /// </summary>
        public static string LinkWhitePapers {
            get {
                return ResourceManager.GetString("LinkWhitePapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your name?.
        /// </summary>
        public static string MainPageFormQuestion1 {
            get {
                return ResourceManager.GetString("MainPageFormQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your name.
        /// </summary>
        public static string MainPageFormQuestion1Placeholder {
            get {
                return ResourceManager.GetString("MainPageFormQuestion1Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string MainPageFormQuestion2 {
            get {
                return ResourceManager.GetString("MainPageFormQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string MainPageFormQuestion3 {
            get {
                return ResourceManager.GetString("MainPageFormQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your problem or message.
        /// </summary>
        public static string MainPageFormQuestion4 {
            get {
                return ResourceManager.GetString("MainPageFormQuestion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your problem or message.
        /// </summary>
        public static string MainPageFormQuestion4Placeholder {
            get {
                return ResourceManager.GetString("MainPageFormQuestion4Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s upgrade your business!.
        /// </summary>
        public static string MainPegeFormTitle {
            get {
                return ResourceManager.GetString("MainPegeFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Qoute.
        /// </summary>
        public static string NavBarRequestQoute {
            get {
                return ResourceManager.GetString("NavBarRequestQoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Qoute.
        /// </summary>
        public static string RequestQoute {
            get {
                return ResourceManager.GetString("RequestQoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are your best IT solutions provider.
        /// </summary>
        public static string SliderSlide1 {
            get {
                return ResourceManager.GetString("SliderSlide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing Solutions.
        /// </summary>
        public static string SliderSlide2 {
            get {
                return ResourceManager.GetString("SliderSlide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology solution.
        /// </summary>
        public static string SliderSlide3 {
            get {
                return ResourceManager.GetString("SliderSlide3", resourceCulture);
            }
        }
    }
}
