// <auto-generated />
namespace DigitalLeader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogModelUpdatedintbugfixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogModelUpdatedintbugfixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201701111520529_BlogModelUpdated-int-bug-fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
